backend:
  name: "git-gateway"
  branch: "main"
publish_mode: "editorial_workflow"
media_folder: "static/media"
public_folder: "./media"
collections:
  - name: "english_work"
    label: "Work (English)"
    folder: "content/work"
    create: true
    slug: "{{id}}"
    identifier_field: id
    extension: "json"
    filter:
      field: "language"
      value: "en-GB"
    fields:
      - label: "Name"
        name: "name"
        widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "Gallery"
        name: "galley"
        widget: "list"
        required: false
        field:
          label: "File"
          name: "file"
          widget: "file"
      - label: "ID"
        name: "id"
        widget: "string"
  - name: "spanish_work"
    label: "Trabajo (Español)"
    folder: "content/work"
    create: true
    slug: "{{id}}"
    identifier_field: id
    extension: "json"
    filter:
      field: "language"
      value: "es-AR"
    fields:
      - label: "Nombre"
        name: "name"
        widget: "string"
      - label: "Cuerpo"
        name: "body"
        widget: "markdown"
      - label: "Gallery"
        name: "galley"
        widget: "list"
        required: false
        field:
          label: "Archivo"
          name: "file"
          widget: "file"
      - label: "ID"
        name: "id"
        widget: "string"
  - label: "Menu"
    name: "menu"
    files:
      - name: "english_menu"
        label: "Menu (English)"
        file: "content/english_menu.json"
        extension: "json"
        fields:
          - label: "Items (English)"
            name: "items"
            widget: "list"
            field:
              label: "Item (English)"
              name: "item"
              widget: "relation"
              collection: "english_work"
              value_field: "id"
              search_fields: ["name"]
              display_fields: ["name"]
      - name: "spanish_menu"
        label: "Menú (Español)"
        file: "content/spanish_menu.json"
        extension: "json"
        fields:
          - label: "Ítems (Español)"
            name: "items"
            widget: "list"
            field:
              label: "Ítem (Español)"
              name: "item"
              widget: "relation"
              collection: "spanish_work"
              value_field: "id"
              search_fields: ["name"]
              display_fields: ["name"]
