backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "static/media"
public_folder: "./media"
collections:
  - name: "works"
    label: "Works" # Used in the UI
    folder: "content/works" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Photo", name: "photo", widget: "image", media_library: {config: {multiple: true}}}
      - {label: "Video", name: "video", widget: "file", media_library: {config: {multiple: true}}}
