backend:
  name: "git-gateway"
  branch: "main"
publish_mode: "editorial_workflow"
media_folder: "static/media"
public_folder: "./media"
collections:
  - name: "english_work"
    label: "Work (English)"
    folder: "content/work"
    create: true
    slug: "{{slug}}"
    identifier_field: name
    extension: "json"
    filter:
      field: "language"
      value: "en-GB"
    fields:
      - name: "name"
        label: "Name"
        widget: "string"
      - name: "body"
        label: "Body"
        widget: "markdown"
      - name: "galley"
        label: "Gallery"
        widget: "list"
        required: false
        field:
          name: "file"
          label: "File"
          widget: "file"
      - name: "language"
        label: "Language"
        widget: "hidden"
        default: "en-GB"
  - name: "spanish_work"
    label: "Trabajo (Español)"
    folder: "content/work"
    create: true
    slug: "{{slug}}"
    identifier_field: name
    extension: "json"
    filter:
      field: "language"
      value: "es-AR"
    fields:
      - name: "name"
        label: "Nombre"
        widget: "string"
      - name: "body"
        label: "Cuerpo"
        widget: "markdown"
      - name: "galley"
        label: "Gallery"
        widget: "list"
        required: false
        field:
          name: "file"
          label: "Archivo"
          widget: "file"
      - name: "language"
        label: "Lenguaje"
        widget: "hidden"
        default: "es-AR"
  - name: "menu"
    label: "Menu"
    files:
      - name: "english_menu"
        label: "Menu (English)"
        file: "content/english_menu.json"
        extension: "json"
        filter:
          field: "language"
          value: "en-GB"
        fields:
          - name: "items"
            label: "Items"
            widget: "list"
            field:
              name: "item"
              label: "Item"
              widget: "relation"
              collection: "english_work"
              value_field: "{{name}}|{{slug}}"
              search_fields: ["name"]
              display_fields: ["name"]
          - name: "language"
            label: "Language"
            widget: "hidden"
            default: "en-GB"
      - name: "spanish_menu"
        label: "Menú (Español)"
        file: "content/spanish_menu.json"
        extension: "json"
        filter:
          field: "language"
          value: "es-AR"
        fields:
          - name: "items"
            label: "Ítems"
            widget: "list"
            field:
              name: "item"
              label: "Ítem"
              widget: "relation"
              collection: "spanish_work"
              value_field: "{{name}}|{{slug}}"
              search_fields: ["name"]
              display_fields: ["name"]
          - name: "language"
            label: "Lenguaje"
            widget: "hidden"
            default: "es-AR"
  - name: "constants"
    label: "Constants"
    files:
      - name: "english_constants"
        label: "Constants (English)"
        file: "content/english_constants.json"
        extension: "json"
        filter:
          field: "language"
          value: "en-GB"
        fields:
          - name: "title"
            label: "Title"
            widget: "string"
          - name: "description"
            label: "Description"
            widget: "string"
          - name: "language"
            label: "Language"
            widget: "hidden"
            default: "en-GB"
      - name: "spanish_constants"
        label: "Constantes (Español)"
        file: "content/spanish_constants.json"
        extension: "json"
        filter:
          field: "language"
          value: "es-AR"
        fields:
          - name: "title"
            label: "Título"
            widget: "string"
          - name: "description"
            label: "Descripción"
            widget: "string"
          - name: "language"
            label: "Lenguaje"
            widget: "hidden"
            default: "es-AR"