backend:
  name: 'git-gateway'
  branch: 'main'
publish_mode: 'editorial_workflow'
media_folder: 'content/media'
public_folder: './'
collections:
  - name: 'english_work'
    label: 'Work (English)'
    folder: 'content/work'
    create: true
    slug: '{{slug}}'
    identifier_field: name
    extension: 'json'
    filter:
      field: 'language'
      value: 'en-GB'
    fields:
      - name: 'name'
        label: 'Name'
        widget: 'string'
      - name: 'description'
        label: 'Description'
        widget: 'text'
      - name: 'body'
        label: 'Body'
        widget: 'markdown'
      - name: 'gallery'
        label: 'Gallery'
        widget: 'list'
        required: false
        fields:
          - name: 'file'
            label: 'File'
            widget: 'file'
          - name: 'description'
            label: 'Description'
            widget: 'text'
      - name: 'language'
        widget: 'hidden'
        default: 'en-GB'
  - name: 'spanish_work'
    label: 'Work (Español)'
    folder: 'content/obra'
    create: true
    slug: '{{slug}}'
    identifier_field: name
    extension: 'json'
    filter:
      field: 'language'
      value: 'es-AR'
    fields:
      - name: 'name'
        label: 'Name'
        widget: 'string'
      - name: 'description'
        label: 'Description'
        widget: 'text'
      - name: 'body'
        label: 'Body'
        widget: 'markdown'
      - name: 'gallery'
        label: 'Gallery'
        widget: 'list'
        required: false
        fields:
          - name: 'file'
            label: 'File'
            widget: 'file'
          - name: 'description'
            label: 'Description'
            widget: 'text'
      - name: 'language'
        widget: 'hidden'
        default: 'es-AR'
  - name: 'chinese_work'
    label: 'Work (汉语)'
    folder: 'content/艺术品'
    create: true
    slug: '{{slug}}'
    identifier_field: name
    extension: 'json'
    filter:
      field: 'language'
      value: 'zh-CN'
    fields:
      - name: 'name'
        label: 'Name'
        widget: 'string'
      - name: 'description'
        label: 'Description'
        widget: 'text'
      - name: 'body'
        label: 'Body'
        widget: 'markdown'
      - name: 'gallery'
        label: 'Gallery'
        widget: 'list'
        required: false
        fields:
          - name: 'file'
            label: 'File'
            widget: 'file'
          - name: 'description'
            label: 'Description'
            widget: 'text'
      - name: 'language'
        widget: 'hidden'
        default: 'zh-CN'
  - name: 'constants'
    label: 'Constants'
    files:
      - name: 'english_constants'
        label: 'Constants (English)'
        file: 'content/english_constants.json'
        extension: 'json'
        fields:
          - name: 'language'
            widget: 'hidden'
            default: 'en-GB'
          - name: 'title'
            label: 'Title'
            widget: 'string'
          - name: 'description'
            label: 'Description'
            widget: 'text'
          - name: 'footer'
            label: 'Footer'
            widget: 'markdown'
          - name: 'i18n_string_menu'
            widget: 'hidden'
            default: 'Menu'
          - name: 'i18n_string_gallery_action'
            widget: 'hidden'
            default: 'Select photo number'
          - name: 'i18n_string_social'
            widget: 'string'
            default: 'B side'
          - name: 'i18n_string_social_action'
            widget: 'hidden'
            default: 'See all posts'
          - name: 'i18n_string_about'
            widget: 'string'
            default: 'About'
          - name: 'i18n_string_shows'
            widget: 'string'
            default: 'Shows'
          - name: 'i18n_string_works'
            widget: 'string'
            default: 'Works'
          - name: 'menu'
            label: 'Menu'
            widget: 'list'
            field:
              name: 'item'
              label: 'Item'
              widget: 'relation'
              collection: 'english_work'
              value_field: '{{name}}|{{slug}}'
              search_fields: ['name']
              display_fields: ['name']
          - name: 'secondary_menu'
            label: 'Secondary Menu'
            widget: 'list'
            field:
              name: 'item'
              label: 'Item'
              widget: 'relation'
              collection: 'english_work'
              value_field: '{{name}}|{{slug}}'
              search_fields: ['name']
              display_fields: ['name']
          - name: 'gallery'
            label: 'Gallery'
            widget: 'list'
            fields:
              - name: 'file'
                label: 'File'
                widget: 'file'
              - name: 'description'
                label: 'Description'
                widget: 'text'
              - name: 'work'
                label: 'Work'
                widget: 'relation'
                collection: 'english_work'
                value_field: '{{slug}}'
                search_fields: ['name']
                display_fields: ['name']
                required: false
          - name: 'about'
            label: 'About'
            widget: 'markdown'
          - name: 'shows_gallery'
            label: 'Shows'
            widget: 'list'
            fields:
              - name: 'file'
                label: 'File'
                widget: 'file'
              - name: 'description'
                label: 'Description'
                widget: 'text'
              - name: 'work'
                label: 'Work'
                widget: 'relation'
                collection: 'english_work'
                value_field: '{{slug}}'
                search_fields: ['name']
                display_fields: ['name']
                required: false
      - name: 'spanish_constants'
        label: 'Constants (Español)'
        file: 'content/spanish_constants.json'
        extension: 'json'
        fields:
          - name: 'language'
            widget: 'hidden'
            default: 'es-AR'
          - name: 'title'
            label: 'Title'
            widget: 'string'
          - name: 'description'
            label: 'Description'
            widget: 'text'
          - name: 'footer'
            label: 'Footer'
            widget: 'markdown'
          - name: 'i18n_string_menu'
            widget: 'hidden'
            default: 'Menú'
          - name: 'i18n_string_gallery_action'
            widget: 'hidden'
            default: 'Seleccionar foto número'
          - name: 'i18n_string_social'
            widget: 'string'
            default: 'Lado B'
          - name: 'i18n_string_social_action'
            widget: 'hidden'
            default: 'Ver todos los posts'
          - name: 'i18n_string_about'
            widget: 'string'
            default: 'Acerca'
          - name: 'i18n_string_shows'
            widget: 'string'
            default: 'Muestras'
          - name: 'i18n_string_works'
            widget: 'string'
            default: 'Obras'
          - name: 'menu'
            label: 'Menu'
            widget: 'list'
            field:
              name: 'item'
              label: 'Item'
              widget: 'relation'
              collection: 'spanish_work'
              value_field: '{{name}}|{{slug}}'
              search_fields: ['name']
              display_fields: ['name']
          - name: 'secondary_menu'
            label: 'Secondary Menu'
            widget: 'list'
            field:
              name: 'item'
              label: 'Item'
              widget: 'relation'
              collection: 'spanish_work'
              value_field: '{{name}}|{{slug}}'
              search_fields: ['name']
              display_fields: ['name']
          - name: 'gallery'
            label: 'Gallery'
            widget: 'list'
            fields:
              - name: 'file'
                label: 'File'
                widget: 'file'
              - name: 'description'
                label: 'Description'
                widget: 'text'
              - name: 'work'
                label: 'Work'
                widget: 'relation'
                collection: 'spanish_work'
                value_field: '{{slug}}'
                search_fields: ['name']
                display_fields: ['name']
                required: false
          - name: 'about'
            label: 'About'
            widget: 'markdown'
          - name: 'shows_gallery'
            label: 'Shows'
            widget: 'list'
            fields:
              - name: 'file'
                label: 'File'
                widget: 'file'
              - name: 'description'
                label: 'Description'
                widget: 'text'
              - name: 'work'
                label: 'Work'
                widget: 'relation'
                collection: 'spanish_work'
                value_field: '{{slug}}'
                search_fields: ['name']
                display_fields: ['name']
                required: false
      - name: 'chinese_constants'
        label: 'Constants (汉语)'
        file: 'content/chinese_constants.json'
        extension: 'json'
        fields:
          - name: 'language'
            widget: 'hidden'
            default: 'zh-CN'
          - name: 'title'
            label: 'Title'
            widget: 'string'
          - name: 'description'
            label: 'Description'
            widget: 'text'
          - name: 'footer'
            label: 'Footer'
            widget: 'markdown'
          - name: 'i18n_string_menu'
            widget: 'hidden'
            default: '菜单'
          - name: 'i18n_string_gallery_action'
            widget: 'hidden'
            default: '选择照片编号'
          - name: 'i18n_string_social'
            widget: 'string'
            default: 'B面'
          - name: 'i18n_string_social_action'
            widget: 'hidden'
            default: '查看所有帖子'
          - name: 'i18n_string_about'
            widget: 'string'
            default: '关于'
          - name: 'i18n_string_shows'
            widget: 'string'
            default: '艺术展览'
          - name: 'i18n_string_works'
            widget: 'string'
            default: '艺术品'
          - name: 'menu'
            label: 'Menu'
            widget: 'list'
            field:
              name: 'item'
              label: 'Item'
              widget: 'relation'
              collection: 'english_work'
              value_field: '{{name}}|{{slug}}'
              search_fields: ['name']
              display_fields: ['name']
          - name: 'secondary_menu'
            label: 'Secondary Menu'
            widget: 'list'
            field:
              name: 'item'
              label: 'Item'
              widget: 'relation'
              collection: 'chinese_work'
              value_field: '{{name}}|{{slug}}'
              search_fields: ['name']
              display_fields: ['name']
          - name: 'gallery'
            label: 'Galley'
            widget: 'list'
            fields:
              - name: 'file'
                label: 'File'
                widget: 'file'
              - name: 'description'
                label: 'Description'
                widget: 'text'
              - name: 'work'
                label: 'Work'
                widget: 'relation'
                collection: 'chinese_work'
                value_field: '{{slug}}'
                search_fields: ['name']
                display_fields: ['name']
                required: false
          - name: 'about'
            label: 'About'
            widget: 'markdown'
          - name: 'shows_gallery'
            label: 'Shows'
            widget: 'list'
            fields:
              - name: 'file'
                label: 'File'
                widget: 'file'
              - name: 'description'
                label: 'Description'
                widget: 'text'
              - name: 'work'
                label: 'Work'
                widget: 'relation'
                collection: 'chinese_work'
                value_field: '{{slug}}'
                search_fields: ['name']
                display_fields: ['name']
                required: false
