backend:
  name: "git-gateway"
  branch: "main"
publish_mode: "editorial_workflow"
media_folder: "static/media"
public_folder: "./media"
collections:
  - name: "work"
    label: "Work"
    folder: "content/work"
    create: true
    slug: "{{name}}"
    extension: "json"
    fields:
      - label: "Name"
        name: "name"
        widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "Photo"
        name: "photo"
        widget: "image"
        allow_multiple: true
        media_library:
          config:
            multiple: true
      - label: "Video"
        name: "video"
        widget: "file"
        allow_multiple: true
        media_library:
          config:
            multiple: true
