name: Optimize media assets

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.2.0
        with:
          cache: 'npm'
      - run: npm install
      - name: Install ImageMagick
        run: sudo apt install imagemagick

      - name: Optimize media assets
        run: bin/optimize
