name: Optimize media assets

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.2.0
        with:
          cache: npm
      - run: npm install
      - name: Install ImageMagick
        run: sudo apt install imagemagick

      - name: Optimize media assets
        run: bin/optimize

      - name: Commit changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add --all
          git commit -m "Automated media assets optimization"
          git push
